export const ProjectsData=
[
    {
        projectTitle:"Muscle Magic",
        projectDescription:"Muscle Magic is a local multiplayer brawler in which you play as powerful, muscular wizards and barrage your opponents with a variety of wacky spells. Grab up to 3 of your friends and duke it out to see who is truly the fittest mage of them all!",
        projectPage:"https://store.steampowered.com/app/1061150/Muscle_Magic/",
        projectDirectory:"projects/MuscleMagic/",
        projectTeamSize:"20+",
        projectEngine:"Unreal 4",
        projectYear:"2019",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:5,
        projectTrailerLink:"https://www.youtube.com/embed/XtOX2gqb1wE",
    },
    {
        projectTitle:"To The Core",
        projectDescription:"To the Core is a roguelite action-platforming speedrunner. Run, jump and dash your way through levels filled with obstacles and hazards. Fight through heaps of enemies to save your father and set record times",
        projectPage:"https://store.steampowered.com/app/874030/To_the_Core/",
        projectDirectory:"projects/ToTheCore/",
        projectTeamSize:"20+",
        projectEngine:"Unreal 4",
        projectYear:"2018",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:6,
        projectTrailerLink:"https://www.youtube.com/embed/Zq4nqB4I4EM",
    },
    {
        projectTitle:"Random Racing",
        projectDescription:"A racing game inspired by Mario Kart",
        projectPage:"https://store.steampowered.com/app/1061150/Muscle_Magic/",
        projectDirectory:"projects/RandomRacing/",
        projectTeamSize:"4",
        projectEngine:"Unity3D",
        projectYear:"2015",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:4,
        projectTrailerLink:"",
    },
    {
        projectTitle:"Muscle Magic",
        projectDescription:"Muscle Magic is a local multiplayer brawler in which you play as powerful, muscular wizards and barrage your opponents with a variety of wacky spells. Grab up to 3 of your friends and duke it out to see who is truly the fittest mage of them all!",
        projectPage:"https://store.steampowered.com/app/1061150/Muscle_Magic/",
        projectDirectory:"projects/MuscleMagic/",
        projectTeamSize:"20+",
        projectEngine:"Unreal 4",
        projectYear:"2019",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:5,
        projectTrailerLink:"https://www.youtube.com/embed/XtOX2gqb1wE",
    },
    {
        projectTitle:"To The Core",
        projectDescription:"To the Core is a roguelite action-platforming speedrunner. Run, jump and dash your way through levels filled with obstacles and hazards. Fight through heaps of enemies to save your father and set record times",
        projectPage:"https://store.steampowered.com/app/874030/To_the_Core/",
        projectDirectory:"projects/ToTheCore/",
        projectTeamSize:"20+",
        projectEngine:"Unreal 4",
        projectYear:"2018",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:6,
        projectTrailerLink:"https://www.youtube.com/embed/Zq4nqB4I4EM",
    },
    {
        projectTitle:"Random Racing",
        projectDescription:"A racing game inspired by Mario Kart",
        projectPage:"https://store.steampowered.com/app/1061150/Muscle_Magic/",
        projectDirectory:"projects/RandomRacing/",
        projectTeamSize:"4",
        projectEngine:"Unity3D",
        projectYear:"2015",
        projectDevStory:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        screenshotCount:4,
        projectTrailerLink:"",
    },
]